name: Build and deploy
run-name: >
  "${{ github.event.head_commit.message }}" ${{ github.event_name }}ed by ${{ github.actor }}

on:
  push:
    branches:
      - staging
      - production

jobs:
  build-and-deploy:
    runs-on: ubuntu-22.04

    steps:
      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version: "18"

      - name: Checkout code
        uses: actions/checkout@v5

      - name: Install dependencies
        run: npm install --ignore-scripts
        env:
          npm_config_registry: https://registry.npmjs.org/

      - name: Build frontend
        run: npm run build
        env:
          NODE_OPTIONS: --openssl-legacy-provider

      - name: Zip frontend
        run: zip -r wwdb.zip dist/index.html dist/scouts-wwdb.js dist/scouts-wwdb.js.map dist/favicon.ico

      - name: Generate branch-specific tag
        id: tag
        run: |
          BRANCH=${{ github.ref_name }}
          TAG="${BRANCH//\//-}-latest"
          echo "tag=$TAG" >> $GITHUB_OUTPUT

      - name: Delete existing tag (if exists)
        run: |
          git push origin :refs/tags/${{ steps.tag.outputs.tag }} || true

      - name: Zzzz...
        uses: GuillaumeFalourd/wait-sleep-action@v1
        with:
          time: "60" # for 60 seconds

      - name: Create a release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "be-content.zip"
          makeLatest: true
          tag: ${{ steps.tag.outputs.tag }}

      - name: Deploy
        uses: appleboy/ssh-action@v1
        env:
          BRANCH_NAME: ${{ github.ref_name }}
        with:
          command_timeout: 30m
          proxy_timeout: 3m
          proxy_host: ${{ secrets.PROXYHOST }}
          proxy_username: ${{ secrets.USER }}
          proxy_key: ${{ secrets.KEY }}
          proxy_port: ${{ secrets.PROXYPORT }}
          host: ${{ secrets.SSHHOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.SSHPORT }}
          envs: BRANCH_NAME
          script: |
            echo "Branch $BRANCH_NAME"
            sudo -u ansible /opt/deploy-wwdb.sh frontend ${BRANCH_NAME}

